apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bgd-base
namePrefix: prod-
commonLabels:
  environment: prod

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: blue
    target:
      group: apps
      version: v1
      kind: Deployment
      name: bgd
